Numpy does not return matrix in fraction form

In [2]:
import numpy as np


Initialize a matrix in numpy

In [ ]:
a = np.matrix('-2,3;-5,3')

In [ ]:
print(a)

[[ 6 -5 -4]
 [-6 -5 -2]]


In [ ]:
b = np.matrix('8,-8;-5,2')

In [ ]:
print(b)

[[ 5 -4]
 [-8  6]
 [-8 -3]]


Matrix Multiply in numpy

In [ ]:
np.matmul(a,b)

matrix([[-31,  22],
        [-55,  46]])

In [ ]:
np.matmul(b,a)

matrix([[ 54,  -5, -12],
        [-84,  10,  20],
        [-30,  55,  38]])

In [ ]:
print(a)

[[4 5]
 [0 4]]


In [ ]:
a2 = np.matmul(a,a) 

In [ ]:
a3 = np.matmul(a2,a)

In [ ]:
print(a3)

[[ 64 240]
 [  0  64]]


In [ ]:
a = np.matrix('1,-2,1;-1,1,-1;1,-2,0')

In [ ]:
b = np.matrix('2,2,1;1,1,0;-1,-2,-1')

In [ ]:
print(np.matmul(a,b))

[[-1 -2  0]
 [ 0  1  0]
 [ 0  0  1]]


Inverse of Matrix in NP

In [ ]:
ainv = np.linalg.inv(a)

In [ ]:
print(ainv)

[[-2. -2.  1.]
 [-1. -1. -0.]
 [ 1. -0. -1.]]


In [ ]:
a = np.matrix('-2,-3,2;-6,-7,3;4,10,-7')

In [ ]:
print(np.linalg.inv(a))

[[-1.58333333  0.08333333 -0.41666667]
 [ 2.5        -0.5         0.5       ]
 [ 2.66666667 -0.66666667  0.33333333]]


Sympy import & Matrix initialization

In [2]:
from sympy import * 
M = Matrix([[0,-3,-2, 7],[2,-1,0,-3],[-2,0,1,2]])

In [24]:
Matrix([[-9,7],[-7,-9]])

Matrix([
[-9,  7],
[-7, -9]])

In [40]:
M**3


Matrix([
[  594, 1358],
[-1358,  594]])

Reduced Row Echelon Form


In [9]:
M_rref = M.rref()
print("Matrix : {} ".format(M.rref()))


Matrix : (Matrix([
[1, 0],
[0, 1]]), (0, 1)) 


In [10]:
a = Matrix([[3,2],[-2,-1]])

In [11]:
a1 = Matrix([[0,-1],[1,-3]])

In [12]:
a1*a**-1

Matrix([
[-2,  -3],
[-7, -11]])

In [13]:
b = Matrix([[2,2,-1],[1,0,1],[1,1,0]])

Anti-Diagonalization

In [14]:
P = Matrix([[6,9],[0,3]])

In [15]:
D = Matrix([[0,0],[0,1]])

In [16]:
P*D*(P**-1)

Matrix([
[0, 3],
[0, 1]])

In [17]:
M

Matrix([
[-9,  7],
[-7, -9]])

In [18]:
M.rref()

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

Inverse Matrix

In [19]:
(b**-1)*a

ShapeError: Matrix size mismatch: (3, 3) * (2, 2).

In [ ]:
b.inv()*a

⎡3   -4  2 ⎤
⎢          ⎥
⎢-4  5   -2⎥
⎢          ⎥
⎣-4  4   -1⎦

EigenStuff

In [ ]:
E = Matrix([[7,-8],[6,8]])

In [ ]:
E

Matrix([
[7, -8],
[6,  8]])

[eigenvalue, multiplicity, {eigenspace}]

In [ ]:
E.eigenvects()

[(15/2 - sqrt(191)*I/2,
  1,
  [Matrix([
   [-1/12 - sqrt(191)*I/12],
   [                     1]])]),
 (15/2 + sqrt(191)*I/2,
  1,
  [Matrix([
   [-1/12 + sqrt(191)*I/12],
   [                     1]])])]

# Orthogonal Projection

In [18]:
y = Matrix([[0,-1,0,0]])

In [19]:
u1 = Matrix([[-1,1,-1,1]])
u2 = Matrix([[-1,1,1,-1]])
u3 = Matrix([[1,1,1,1]])

In [20]:
c_1 = (y.dot(u1))/((u1).dot(u1))
c_2 = (y.dot(u2))/((u2).dot(u2))
c_3 = (y.dot(u3))/((u3).dot(u3))



In [21]:
c_1*u1 + c_2*u2 + c_3*u3

Matrix([[1/4, -3/4, -1/4, -1/4]])

In [16]:
print(u1.dot(u3))

0
